version: "3.9"

services:
  web:
    build: ./frontend
    ports:
      - "5173:5173"

  api:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DB_URL=mongodb://db:27017/
    depends_on:
      - db

  db:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - testDB:/data/db

volumes:
  testDB:
